name: contextual_menu
description: This plugin allows Flutter desktop apps to create native context menus.
version: 0.1.3
homepage: https://github.com/leanflutter/contextual_menu

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  menu_base: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  dependency_validator: ^3.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: ContextualMenuPlugin
      macos:
        pluginClass: ContextualMenuPlugin
      windows:
        pluginClass: ContextualMenuPlugin
