name: contextual_menu
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  menu_base:
    path: ../menu_base

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: ContextualMenuPlugin
      macos:
        pluginClass: ContextualMenuPlugin
      windows:
        pluginClass: ContextualMenuPlugin
